all:
	javac *.java
	#javac AddSensors.java
	#javac BTFToATF.java
	#javac CircularBufferEnumeration.java
	#javac CircularBufferException.java
	#javac CircularBuffer.java
	#javac DialogMessage.java
	#javac DialogMessageJoke.java
	##javac FastKNN.java
	#javac FilenameFilterByEnding.java
	#javac JCyeException.java
	#javac KNN.java
	#javac Probability.java
	#javac TBVersion.java
	#javac TrackFile.java
	#javac Units.java
	#javac Vec2.java
